---
- name: Install and configure Zabbix agent
  hosts: client_servers
  become: true

  tasks:
  - name: Install Zabbix
       apt:
       name: zabbix-agent
       state: present
 
- name: Configure Zabbix agent
  lineinfile:
     path: /etc/zabbix/zabbix_agentd.conf
     regexp: "{{ item.regexp }}"
     line: "{{ item.line }}"
     notify:
     - restart zabbix-agent

- name: Enable and start Zabbix agent service
  service:
   name: zabbix-agent
   state: started
   enabled: yes

   handlers:
   - name: restart zabbix-agent
     service:
       name: zabbix-agent
       state: restarted