- name: Install and configure Zabbix agent
  hosts: all
  become: yes
  vars:
    zabbix_server: "158.160.26.37"
    zabbix_hostname: "{{ ansible_hostname }}"
  tasks:
    - name: Download Zabbix Agent .deb package
      get_url:
        url: https://www.techplanet.pro/d/pool/main/z/zabbix/zabbix-agent2_5.0.29-1%2Bfocal_amd64.deb
        dest: /tmp/zabbix-agent2_5.0.29-1+focal_amd64.deb
    - name: Install Zabbix Agent
      apt:
       deb: /tmp/zabbix-agent2_5.0.29-1+focal_amd64.deb

    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^Server=', line: 'Server={{ zabbix_server }}' }
        - { regexp: '^Hostname=', line: 'Hostname={{ zabbix_hostname }}' }


    - name: Start and enable Zabbix agent service
      service:
        name: zabbix-agent2
        state: started
        enabled: true